# Generated by Django 2.1 on 2018-08-28 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180828_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_pages',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
