# Generated by Django 2.1 on 2018-08-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'fiction'), ('fantasy', 'fantasy'), ('art', 'art')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
