# Generated by Django 2.1 on 2018-08-28 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_pages',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
